# Generated by Django 4.1.6 on 2023-02-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_data_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='second_name',
            new_name='lastname',
        ),
    ]
