# Generated by Django 4.1.6 on 2023-02-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_first_name_member_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='joined_data',
            new_name='joined_date',
        ),
    ]
